version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: cv_parser_postgres
    environment:
      POSTGRES_DB: cv_parser_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  spring-app:
    build: .
    container_name: cv_parser_app
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/cv_parser_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres-db

volumes:
  pgdata: