spring.datasource.url=jdbc:postgresql://localhost:5432/cv_parser_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:2468}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=true
server.port=9090
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mikayilovarufan@gmail.com
spring.mail.password=${MAIL_PASSWORD:Rufana2468}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true